<?php
// Variables
return [
  "creatorName" => "SZM",
  "creatorUrl" => "https://shehlizah.com",
  "templateName" => "Jobsease",
  "templateSuffix" => "AI-Powered Resume & Career Platform",
  "templateVersion" => "1.0.0",
  "templateFree" => true,
  "templateDescription" => "Jobsease - Your complete AI-powered career platform. Create professional resumes, generate cover letters, find jobs, and prepare for interviews with AI assistance.",
  "templateKeyword" => "ai resume builder, cover letter generator, job finder, interview prep, career tools, resume templates, ai career assistant",
  "licenseUrl" => "https://shehlizah.com/license/",
  "livePreview" => "https://jobsease.com/",
  "productPage" => "https://jobsease.com/",
  "ogTitle" => "Jobsease - AI-Powered Career Platform",
  "ogType" => "product",
  "ogImage" => "https://github-production-user-asset-6210df.s3.amazonaws.com/61959920/427962312-a4f2c59c-92a0-4624-a0f0-d53ee0acf7d9.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVCODYLSA53PQK4ZA%2F20250328%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250328T104541Z&X-Amz-Expires=300&X-Amz-Signature=88f19338f62219496631c44f4da216a3f2da10169fb75377cdc9146dc1722352&X-Amz-SignedHeaders=host",
  "support" => "https://github.com/shehlizah/jobsease/issues",
  "moreThemes" => "https://shehlizah.com/",
  "documentation" => "https://jobsease.com/docs",
  "repository" => "https://github.com/shehlizah/jobsease",
  "gitRepo" => "https://github.com/shehlizah/jobsease.git",
  "gitRepoAccess" => "https://github.com/shehlizah",
  "githubFreeUrl" => "https://github.com/shehlizah",
  "facebookUrl" => "https://www.facebook.com/shehlizah/",
  "twitterUrl" => "https://x.com/shehlizah",
  "githubUrl" => "https://github.com/shehlizah",
  "dribbbleUrl" => "https://dribbble.com/shehlizah",
  "instagramUrl" => "https://www.instagram.com/shehlizah/"
];
